export global Animation {
  out property <angle> sway-idle1: 1.6deg * sin(animation-tick() / 10s * 360deg);
  out property <angle> sway-idle2: 1.3deg * sin(animation-tick() / 11s * 360deg);

  out property <angle> h-hand-idle: animation-tick() / 5.4s * 360deg;
  out property <angle> m-hand-idle: animation-tick() / 930ms * 360deg;

  // out property <angle> h-hand-idle: animation-tick() / 5.4s * 360deg;
  // out property <angle> m-hand-idle: animation-tick() / 5s * 360deg;
}