import { Timecard } from "timecard.slint";
import { TimeClock } from "time-clock.slint";
import { Animation } from "animations.slint";

import { Button } from "std-widgets.slint";

export component AppWindow inherits Window {
  // bubbled properties
  in-out property <angle> h-hand-angle <=> tc.transform-rotation;
  in-out property <angle> m-hand-angle <=> tc.transform-rotation;

  width: 600px;
  height: 500px;

  ta-root := TouchArea {}

  Image {
    opacity: 0.28;
    width: root.width;
    source: @image-url("../assets/images/vhs_filter.jpg");
    z: 999; // ensure this element is on top of others
  }

  Image {
    height: (root.height / 1px) * 1px;
    source: @image-url("../assets/images/background2.jpg");
  }

  VerticalLayout {
    alignment: center;
    HorizontalLayout  {
      height: root.height / 1.5;
      spacing: 50px;
      padding: 8px;
      alignment: center;

      // time clock
      tc := TimeClock {
        transform-rotation: Animation.sway-idle1;
      }

      // timecard
      tm := Timecard {
        transform-rotation: Animation.sway-idle2;
      }
    }
  }
}
