import { Animation } from "animations.slint";
import "../assets/fonts/the_display_st.ttf";

export component TimeClock inherits Rectangle{
  width: tc-img.width;
  height: tc-img.height;

  tc-area := TouchArea {
    mouse-cursor: not-allowed;
  }
  
  property <length> x-dynm: tc-area.has-hover ? (200px - tc-area.mouse-x) * 0.1 - 3px : 0px;
  property <length> y-dynm: tc-area.has-hover ? (200px - tc-area.mouse-y) * 0.1 - 3px : 0px;

  // drop shadow
  Rectangle {
    drop-shadow-color: black;
    drop-shadow-blur: 23px;

    x: x-dynm;
    y: y-dynm;

    animate x, y {
      duration: 300ms;
      easing: ease-out;
    }
  }

  // clock
  tc-img := Image {
    x: x-dynm;
    y: y-dynm;

    width: 300px;
    source: @image-url("../assets/images/rect_clock.png");

    animate x, y {
      duration: 300ms;
      easing: ease-out;
    }
  }

  // time display
  d-time := Text {
    x: tc-img.x + 28px;
    y: tc-img.y + 12px;

    text: "00:00";
    color: gainsboro;

    font-family: "The Display St";
    font-size: 38px;

    transform-rotation: tc-img.transform-rotation;
  }

  // clock hands
  h-hand := Image {
    x: tc-img.x + (tc-img.width / 2) - 18px;
    y: (tc-img.y + 110px) + 64px;

    width: tc-img.width / 2.7;
    source: @image-url("../assets/images/hour_hand.svg");

    transform-rotation: Animation.h-hand-idle;
    transform-origin: {x: 18.5px, y: self.height / 2};
  }

  m-hand := Image {
    x: tc-img.x + (tc-img.width / 2) - 22px;
    y: (tc-img.y + 110px) + 64px;

    width: tc-img.width / 2.2;
    source: @image-url("../assets/images/minute_hand.svg");

    transform-rotation: Animation.m-hand-idle;
    transform-origin: {x: 20.4px, y: self.height / 2};
  }

  // inner shadow
  Rectangle {
    width: tc-img.width;
    height: tc-img.height;

    x: x-dynm;
    y: y-dynm;

    inner-shadow-blur: 62px;
    inner-shadow-color: black;

    animate x, y {
      duration: 300ms;
      easing: ease-out;
    }
  }
}